function [shg_i,shg_c] = SHG_tensor(o,v,w,r,f,nw,hv,ksi,direct)
% This function evaluates the i-type and c-type SHG tensors
% The input arguments are
% o -      energy difference
% v -      velocity matrix
% w -      second order d2H/dk2 matrix
% r -      position matrix (Berry connection)
% f -      occupation difference
% nw -     total bands
% hv -     photon energy
% ksi -    broadening factor
% direct - direction indices, out, in, in
%
% Here, the i-type is time-reversal even
% The c-type is time-reversal odd
% Both includes inteband and mixed contributions

% thr = 1e-6; % a safe threshold energy difference
nhv = length(hv);
ndir = size(direct,1);
shg_i = zeros(nhv,ndir);
shg_c = zeros(nhv,ndir);
p = eye(nw, nw); % no projection applied for shg

for idir = 1:ndir
    a = direct(idir,1);
    b = direct(idir,2);
    c = direct(idir,3);
    ra = r(:,:,a);
    rb = r(:,:,b);
    rc = r(:,:,c);
    va_diff = diag(real(v(:,:,a))) - diag(real(v(:,:,a)))';
    vb_diff = diag(real(v(:,:,b))) - diag(real(v(:,:,b)))';
    vc_diff = diag(real(v(:,:,c))) - diag(real(v(:,:,c)))';
    rakb = calc_rdk(v,o,w,p,nw,ksi,a,b);
    rakc = calc_rdk(v,o,w,p,nw,ksi,a,c);
    rbka = calc_rdk(v,o,w,p,nw,ksi,b,a);
    rbkc = calc_rdk(v,o,w,p,nw,ksi,b,c);
    rcka = calc_rdk(v,o,w,p,nw,ksi,c,a);
    rckb = calc_rdk(v,o,w,p,nw,ksi,c,b);

    for ihv = 1:nhv
        omega = hv(ihv) + 1i*ksi;
        for m = 1:nw
        for n = 1:nw
        for l = 1:nw
            prefac_inter = ra(n,m)*(rb(m,l)*rc(l,n)+rc(m,l)*rb(l,n)) ...
                .* PV_inverse(o(l,n)-o(m,l),ksi);
            shg_i(ihv,idir) = shg_i(ihv,idir) + real(prefac_inter) ...
                * (2*f(n,m) ./ (o(m,n)-2*omega) ...
                + f(l,n) ./ (o(l,n)-omega) ...
                + f(m,l) ./ (o(m,l)-omega)); % pure interband
            shg_c(ihv,idir) = shg_c(ihv,idir) + 1i* imag(prefac_inter) ...
                * (2*f(n,m) ./ (o(m,n)-2*omega) ...
                + f(l,n) ./ (o(l,n)-omega) ...
                + f(m,l) ./ (o(m,l)-omega)); % pure interband
            % prefac_inter = ra(n,m)*(rb(m,l)*rc(l,n)+rc(m,l)*rb(l,n)) ...
            %     .* PV_inverse(o(l,n)-o(m,l),ksi);
            % shg_i(ihv,idir) = shg_i(ihv,idir) + real(prefac_inter) ...
            %     * (2*f(n,m) .* PV_inverse(o(m,n)-2*omega, ksi) ...
            %     + f(l,n) .* PV_inverse(o(l,n)-omega, ksi) ...
            %     + f(m,l) .* PV_inverse(o(m,l)-omega, ksi)); % pure interband
            % shg_c(ihv,idir) = shg_c(ihv,idir) + imag(prefac_inter) ...
            %     * (2*f(n,m) .* PV_inverse(o(m,n)-2*omega, ksi) ...
            %     + f(l,n) .* PV_inverse(o(l,n)-omega, ksi) ...
            %     + f(m,l) .* PV_inverse(o(m,l)-omega, ksi)); % pure interband
        end
        end
        end
        % mix_num1 = ra.' .* (rbkc + rckb);
        % mix_num2 = rakc.' .* rb + rakb.' .* rc;
        % mix_num3 = ra.' .* (rb .* vc_diff + rc .* vb_diff);
        % mix_num4 = rbka.' .* rc + rcka.' .* rb;
        % mix_num5 = va_diff .* (rb.' .* rc + rc.' .* rb);
        % shg_i(ihv,idir) = shg_i(ihv,idir) ...
        %     - 2*trace(f * (imag(mix_num1) .* PV_inverse(o.*(o-2*omega),ksi) ...
        %     - imag(mix_num2) .* PV_inverse(o.*(o-omega), ksi) ...
        %     - imag(mix_num3) .* PV_inverse(o.^2, ksi).*(PV_inverse(o-omega, ksi)-4*PV_inverse(o-2*omega,ksi)) ...
        %     + imag(mix_num4) .* 0.5*PV_inverse(o.*(o-omega),ksi)));
        % shg_c(ihv,idir) = shg_c(ihv,idir) ...
        %     + 2*trace(f * (real(mix_num1) .* PV_inverse(o.*(o-2*omega),ksi) ...
        %     + real(mix_num2) .* PV_inverse(o.*(o-omega), ksi) ...
        %     + real(mix_num3) .* PV_inverse(o.^2, ksi).*(PV_inverse(o-omega, ksi)-4*PV_inverse(o-2*omega,ksi)) ...
        %     - real(mix_num4) .* 0.5*PV_inverse(o.*(o-omega),ksi) ...
        %     + real(mix_num5) .* 0.25 * PV_inverse(o.^2.*(o-omega), ksi)));
        mix_num1 = ra.' .* (rbkc + rckb);
        mix_num2 = rakc.' .* rb + rakb.' .* rc;
        mix_num3 = ra.' .* (rb .* vc_diff + rc .* vb_diff);
        mix_num4 = rbka.' .* rc + rcka.' .* rb;
        mix_num5 = va_diff .* (rb.' .* rc + rc.' .* rb);
        shg_i(ihv,idir) = shg_i(ihv,idir) ...
            - 2*trace(f * (imag(mix_num1) ./ (o-2*omega) .* PV_inverse(o, ksi) ...
            - imag(mix_num2) ./ (o-omega) .* PV_inverse(o, ksi) ...
            - imag(mix_num3) .* PV_inverse(o.^2, ksi) .* (1./(o-omega)-4./(o-2*omega)) ...
            + imag(mix_num4) ./ (o-omega)/2 .* PV_inverse(o, ksi) ));
        shg_c(ihv,idir) = shg_c(ihv,idir) ...
            + 1i*2*trace(f * (real(mix_num1) ./ (o-2*omega) .* PV_inverse(o, ksi) ...
            + real(mix_num2) ./ (o-omega) .* PV_inverse(o, ksi) ...
            + real(mix_num3) .* PV_inverse(o.^2, ksi).*(1./(o-omega)-4./(o-2*omega)) ...
            - real(mix_num4) ./ (o-omega)/2 .* PV_inverse(o, ksi) ...
            + real(mix_num5) ./ (o-omega)/4 .* PV_inverse(o.^2, ksi) ));
    end

end
end
